version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_NAME=postgres
      - DB_SSLMODE=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data:
